apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
spec:
  selector:
    type: frontend
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort # o frontend precisa ter o nodeport para se comunicar com o meio externo
  # type: LoadBalancer utilizando servicos de cloud ou nginx em maquina virtual